runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /
  script: home.app

- url: /profile
  script: profile.app

- url: /show-profile
  script: show_profile.app

- url: /editprofile
  script: editprofile.app